version: 2.1

jobs:
  buildLatest:
    docker:
      - image: gradle:6.0.1-jdk8
    steps:
      - checkout
      - run: gradle -S buildLatest

  buildUnhandled:
    docker:
      - image: gradle:6.0.1-jdk8
    steps:
      - checkout
      - run: gradle -S buildUnhandled

  buildSpecified:
    docker:
      - image: gradle:6.0.1-jdk8
    steps:
      - checkout
      - run: gradle -S buildSpecified

  publishUnhandledAndLatest:
    docker:
      - image: gradle:6.0.1-jdk8
    steps:
      - checkout
      - run: |
          if [ -z ${CIRCLE_TAG+x} ]; then
            git ls-remote --exit-code origin refs/tags/v"${CIRCLE_BRANCH#release/}"
          fi
          gradle -S publishUnhandled publishLatest

  publishDslCommon:
    docker:
      - image: gradle:6.0.1-jdk8
    steps:
      - checkout
      - run: "gradle -S :dsl-common:publish"

workflows:
  version: 2

  untagged:
    jobs:
      - buildLatest
      - buildUnhandled
      - buildSpecified
  current:
    jobs:
      - publishUnhandledAndLatest
    triggers:
      - schedule:
          cron: 0 5 * * *
          filters: { branches: { only: /^release\/.*/ } }
  all:
    jobs:
      - publishUnhandledAndLatest:
          filters:
            tags: { only: /^v.*/ }
            branches: { only: /x^/ }
      - publishDslCommon:
          filters:
            tags: { only: /^v.*/ }
            branches: { only: /x^/ }
