version: 2.1

jobs:
  build:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle -S generateForAllModule
      - run: "gradle -S :dsl-common:build"

  test:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle -S test
      - run: "gradle -S :dsl-common:test"

  deployForCdk:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: |
          if [ -z ${CIRCLE_TAG+x} ]; then
            git ls-remote --exit-code origin refs/tags/v"${CIRCLE_BRANCH#release/}"
          fi
          gradle -S generateAndUploadForUpdatedCdk

  deployForUpdate:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle -S uploadToBintrayForAllModule
      - run: "gradle -S :dsl-common:bintrayUpload"


workflows:
  version: 2

  untagged:
    jobs:
      - build
      - test
  current:
    jobs:
      - deployForCdk
    triggers:
      - schedule:
          cron: '0 5 * * *'
          filters: { branches: { only: '/^release\/.*/' } }
  all:
    jobs:
      - deployForUpdate:
          filters:
            tags: { only: '/^v.*/' }
            branches: { ignore: '/^.*/' }
