version: 2.1

jobs:
  build:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle build
  test:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle test
  deployForCdk:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle generateAndUploadForUpdatedCdk
  deployForUpdate:
    docker:
      - image: gradle:5.6.0-jdk8
    steps:
      - checkout
      - run: gradle generateAndUploadForAllModule

workflows:
  version: 2
  untagged-build:
    jobs:
      - build
      - test
  check-cdk-update-and-deploy:
    jobs:
      - deployForCdk
    triggers:
      - schedule:
          cron: '0 5 * * *'
          filters: { branches: { only: master } }
  deploy-all:
    jobs:
      - deployForUpdate:
          filters:
            tags: { only: '/^v.*/' }
            branches: {ignore: '/^.*/'}