version: 2.1

jobs:
  buildUnhandled:
    resource_class: large
    docker:
      - image: sdyip/gradle:7.6.1
    steps:
      - checkout
      - run: gradle -S buildUnhandled

  publishUnhandled:
    resource_class: large
    docker:
      - image: sdyip/gradle:7.6.1
    steps:
      - run: |
          apk add --no-cache git openssh-client
      - checkout
      - run: |
          if [ -z ${CIRCLE_TAG+x} ]; then
            git ls-remote --exit-code origin refs/tags/v"${CIRCLE_BRANCH#release/}"
          fi
          gradle -S publishUnhandled

  publishDslCommon:
    resource_class: large
    docker:
      - image: sdyip/gradle:7.6.1
    steps:
      - checkout
      - run: "gradle -S :dsl-common:publish"

workflows:
  version: 2

  untagged:
    jobs:
      - buildUnhandled
  current:
    jobs:
      - publishUnhandled
    triggers:
      - schedule:
          cron: 0 5 * * *
          filters: { branches: { only: /^release\/.*/ } }
      - schedule:
          cron: 52 19 20 8 *
          filters: { branches: { only: /^release\/.*/ } }
  all:
    jobs:
      - publishUnhandled:
          filters:
            tags: { only: /^v.*/ }
            branches: { only: /x^/ }
      - publishDslCommon:
          filters:
            tags: { only: /^v.*/ }
            branches: { only: /x^/ }
